import { Kohde } from '@/types/content';

export const kohteet: Kohde[] = [
  {
    slug: 'kivikolunkatu-7-nokia',
    title: 'Kivikolunkatu 7 A',
    subtitle: 'Asiakkaan näköinen paritalo – tuotantoon optimoituna ja pitkälle valmiina',
    description:
      'Kivikolunkatu 7 A toteutettiin asiakkaan suunnitelmien ja toiveiden pohjalta – ei valmiista talomallista. Hietakulma optimoi rakenteet elementtituotantoon ja vei esivalmistuksen mahdollisimman pitkälle, jotta työmaalle jäi vähemmän rakennettavaa. Kaksi yksitasoista kotia yhdistyvät vain autokatoksen kautta, joten paritalon tehokkuus säilyy mutta asuminen tuntuu omakotitalomaisen yksityiseltä.',
    location: 'Nokia',
    type: 'Paritalo',
    category: 'paritalot',
    customerType: 'Ammattirakennuttaja',
    deliveryScope: 'Rakenne- ja elementtisuunnittelu, tehtaalla maalatut ja ikkunoilla varustetut puuelementit, palo-osastoivat rakenteet, räystäselementit, 53 kattoristikkoa ja asennus',
    year: '2026',
    featured: true,
    heroImage: '/images/kohteet/kivikolunkatu-7/kivikolunkatu-01.webp',
    thumbnailImage: '/images/kohteet/kivikolunkatu-7/kivikolunkatu-01.webp',
    galleryImages: [
      { src: '/images/kohteet/kivikolunkatu-7/kivikolunkatu-01.webp', alt: 'Kivikolunkatu 7 A:n valmis paritalo Nokialla' },
      { src: '/images/kohteet/kivikolunkatu-7/kivikolunkatu-02.webp', alt: 'Kivikolunkadun sisäänkäyntijulkisivu ja autokatos' },
      { src: '/images/kohteet/kivikolunkatu-7/kivikolunkatu-03.webp', alt: 'Kivikolunkadun katettu terassi' },
      { src: '/images/kohteet/kivikolunkatu-7/kivikolunkatu-04.webp', alt: 'Kivikolunkadun valoisa olohuone ja avokeittiö' },
      { src: '/images/kohteet/kivikolunkatu-7/kivikolunkatu-05.webp', alt: 'Kivikolunkadun ruokailu- ja oleskelutila' },
      { src: '/images/kohteet/kivikolunkatu-7/kivikolunkatu-06.webp', alt: 'Kivikolunkadun moderni keittiö' },
      { src: '/images/kohteet/kivikolunkatu-7/kivikolunkatu-07.webp', alt: 'Kivikolunkadun makuuhuone' },
      { src: '/images/kohteet/kivikolunkatu-7/kivikolunkatu-08.webp', alt: 'Kivikolunkadun kylpyhuone' },
      { src: '/images/kohteet/kivikolunkatu-7/kivikolunkatu-09.webp', alt: 'Kivikolunkadun sauna' },
    ],
    facts: [
      'Valmistumisvuosi 2026',
      'Kaksi yksitasoista kotia',
      '107 m² asuintilaa ja 121 m² kokonaisalaa / koti',
      'Koteja yhdistää autokatos — ei yhteistä asuinseinää',
      'Noin 40 m²:n terassi, pääosin katettu',
      '223 mm:n ulkoseinärunko ja U-arvo 0,17 W/m²K',
      'Ulkoverhous loppumaalattu ja ikkunat asennettu elementteihin tehtaalla',
      'Terassien välinen EI30-seinäke ja palokatkoristikko',
      'Poistoilmalämpöpumppu ja vesikiertoinen lattialämmitys',
      '53 kattoristikkoa',
      'Elementtien, ristikoiden ja erikoisrakenteiden asennus',
    ],
    referenceReason:
      'Kivikolunkatu on hyvä esimerkki siitä, ettei elementtirakentaminen rajoita asiakkaan arkkitehtuuria. Asiakkaan suunnitelma muutettiin valmistettavaksi kokonaisuudeksi, jossa tehtaalla loppumaalatut ja ikkunoilla varustetut seinäelementit, palo-osastoinnit, räystäät ja ristikot sopivat yhteen ennen ensimmäistäkään työmaanostoa. Kun sama kumppani vastaa rakenteiden optimoinnista, valmistuksesta ja asennuksesta, rakennuttaja saa vähemmän rajapintoja, ennakoitavamman aikataulun ja nopeasti säältä suojaan saatavan rungon. Lopputulos näyttää asiakkaan suunnittelemalta – mutta rakentuu elementtituotannon tehokkuudella.',
  },
  {
    slug: 'kirjavaisenkatu-40',
    title: 'Huunalan Herttua ja Paroni',
    subtitle: 'Neljätoista kotia, kaksi yhtiötä ja poikkeuksellisen pitkälle viety esivalmistus',
    description:
      'Kirjavaisenkatu 40–42:ssa rakentamisen nopeus suunniteltiin rakenteisiin jo ennen työmaan alkua. Hietakulma valmisti kahden seitsemän asunnon yhtiön asuin- ja talousrakennukset pitkälle valmiiksi Kankaanpään tehtaalla – julkisivuista ja välipohjista terasseihin, parvekkeisiin ja kattoelementteihin. Tarkasti suunniteltu esivalmistus ja toimituslogistiikka auttoivat viemään seitsemän kodin yhtiön valmiiksi noin seitsemässä kuukaudessa.',
    location: 'Tampere',
    type: 'Rivitalo',
    category: 'rivitalot',
    customerType: 'Perustajaurakoitsija',
    deliveryScope: 'Ulko- ja väliseinäelementit, huoneistojen väliset seinät, easi-joist®-välipohjaelementit, terassi-, ulkoporras-, parveke- ja kattoelementit sekä talousrakennusten elementit',
    year: '2025',
    heroImage: '/images/kohteet/kirjavaisenkatu-40/b7-01_DJI_0965-HDR.webp',
    thumbnailImage: '/images/kohteet/kirjavaisenkatu-40/b7-01_DJI_0965-HDR.webp',
    galleryImages: [
      { src: '/images/kohteet/kirjavaisenkatu-40/b7-01_DJI_0965-HDR.webp', alt: 'Kirjavaisenkatu 40 — ilmakuva' },
      { src: '/images/kohteet/kirjavaisenkatu-40/b7-02_DJI_0955-HDR.webp', alt: 'Kirjavaisenkatu 40 — ilmakuva 2' },
      { src: '/images/kohteet/kirjavaisenkatu-40/b7-03_DJI_0935-HDR.webp', alt: 'Kirjavaisenkatu 40 — ilmakuva 3' },
      { src: '/images/kohteet/kirjavaisenkatu-40/b7-04_DJI_0895-HDR.webp', alt: 'Kirjavaisenkatu 40 — ilmakuva 4' },
      { src: '/images/kohteet/kirjavaisenkatu-40/b7-06_B7 musta.webp', alt: 'Kirjavaisenkatu 40 — julkisivu' },
      { src: '/images/kohteet/kirjavaisenkatu-40/b7-07_1KUV0829-HDR.webp', alt: 'Kirjavaisenkatu 40 — sisäkuva 1' },
      { src: '/images/kohteet/kirjavaisenkatu-40/b7-08_1KUV0849-HDR.webp', alt: 'Kirjavaisenkatu 40 — sisäkuva 2' },
      { src: '/images/kohteet/kirjavaisenkatu-40/b7-10_1KUV0904-HDR.webp', alt: 'Kirjavaisenkatu 40 — sisäkuva 3' },
      { src: '/images/kohteet/kirjavaisenkatu-40/b7-11_1KUV0924-HDR.webp', alt: 'Kirjavaisenkatu 40 — sisäkuva 4' },
      { src: '/images/kohteet/kirjavaisenkatu-40/b7-14_1KUV0929-HDR.webp', alt: 'Kirjavaisenkatu 40 — sisäkuva 5' },
      { src: '/images/kohteet/kirjavaisenkatu-40/yleiskuva-1KUV6096-HDR.webp', alt: 'Kirjavaisenkatu 40 — yleiskuva' },
    ],
    facts: [
      'Valmistumisvuosi 2025',
      'Kaksi asunto-osakeyhtiötä, seitsemän kotia kummassakin',
      'Molemmissa asuinrakennukset sekä varasto- ja jätekatoskäyttöön tehty talousrakennus',
      'Aquapanel- ja puuverhoiltuja ulkoseinäelementtejä',
      'Kantavat väliseinäelementit ja huoneistojen väliset seinäelementit',
      'easi-joist®-välipohjapalkkien avoin rakenne helpottaa IV-, sähkö- ja viemärivetojen reititystä',
      'Pitkälle esivalmistetut terassi-, ulkoporras-, parveke- ja kattoelementit',
      'Elementit pakattiin kuljetusvakeille asennusjärjestykseen',
    ],
    referenceReason:
      'Huunalan kokonaisuus kertoo käytännössä, mitä korkea esivalmistusaste merkitsee rakennusliikkeelle. Tehtaalla valmistettiin ulko- ja väliseinien lisäksi easi-joist®-välipohjat sekä terassi-, porras-, parveke- ja kattoelementit. Puuverhouksen rinnalle toteutetut työmaalla rapattavat Aquapanel-pinnat osoittavat, ettei pitkälle viety elementointi tarkoita yksitoikkoista julkisivua. Elementit pakattiin kuljetusvakeille asennusjärjestykseen ja nostettiin Hiabilla suoraan autosta paikoilleen. Työmaalle tämä toi nopeutta, vähemmän välivarastointia ja selkeän etenemisjärjestyksen – rakennuttajalle paremmin hallittavan aikataulun ja laadun.',
  },
  {
    slug: 'leppatie-pori',
    title: 'Verstaantie ja Leppätie, Pori',
    subtitle: 'Noin 50 kotia kahdessa vuodessa – yhdenmukaista laatua toimituksesta toiseen',
    description:
      'Verstaantien ja Leppätien noin 50 kodin kokonaisuudessa onnistuminen perustui toistettavuuteen ilman turhia työmaamuutoksia. Asuntokohtaiset ratkaisut, kalusteiden liittymät ja tekniset yksityiskohdat sovitettiin yhteen jo ennen tuotantoa. Hietakulma valmisti pitkälle viimeistellyt elementit ympäri vuoden Kankaanpäässä ja toimitti ne Poriin asiakkaan asennusaikatahtiin rytmitettyinä kokonaisuuksina.',
    location: 'Pori',
    type: 'Rivitalo',
    category: 'rivitalot',
    customerType: 'Rakennusliike / kiinteistökehittäjä',
    deliveryScope: 'Pitkälle viimeistellyt ulko- ja huoneistojen väliset seinäelementit noin 50 asuntoon ja talousrakennuksiin, terassi-, porras- ja räystäselementit, valmiit palorakenteet sekä rakennuskohtaisia kattoristikkotoimituksia',
    year: '2023–2024',
    heroImage: '/images/kohteet/leppatie-pori/leppatie-verstaantie-01.webp',
    thumbnailImage: '/images/kohteet/leppatie-pori/leppatie-verstaantie-01.webp',
    galleryImages: [
      { src: '/images/kohteet/leppatie-pori/leppatie-verstaantie-01.webp', alt: 'Leppätien eli Verstaantien rivitalokokonaisuus Porissa' },
      { src: '/images/kohteet/leppatie-pori/leppatie-verstaantie-02.webp', alt: 'Leppätien rivitalon sisäänkäyntijulkisivu iltavalossa' },
      { src: '/images/kohteet/leppatie-pori/leppatie-verstaantie-03.webp', alt: 'Leppätien rivitalon lasitetut terassit' },
      { src: '/images/kohteet/leppatie-pori/leppatie-verstaantie-04.webp', alt: 'Leppätien kohteen talousrakennus' },
      { src: '/images/kohteet/leppatie-pori/leppatie-verstaantie-05.webp', alt: 'Leppätien rivitalon terassijulkisivu' },
      { src: '/images/kohteet/leppatie-pori/leppatie-01.webp', alt: 'Leppätie, Pori — julkisivu 1' },
      { src: '/images/kohteet/leppatie-pori/leppatie-02.webp', alt: 'Leppätie, Pori — julkisivu 2' },
      { src: '/images/kohteet/leppatie-pori/leppatie-03.webp', alt: 'Leppätie, Pori — julkisivu 3' },
      { src: '/images/kohteet/leppatie-pori/leppatie-04.webp', alt: 'Leppätie, Pori — piha-alue' },
      { src: '/images/kohteet/leppatie-pori/leppatie-05.webp', alt: 'Leppätie, Pori — yksityiskohta' },
    ],
    facts: [
      'Verstaantien ja Leppätien yhteinen aluekokonaisuus',
      'Noin 50 asuntoa noin kahden vuoden aikana',
      'Asuntokohtaiset yksityiskohdat yhteensovitettu ennen tuotantoa',
      'Ulkoseinäelementit paneloitu ja pintamaalattu tehtaalla',
      'Pitkälle viimeistellyt räystäselementit',
      'Huoneistojen välisiä seinä-, terassi- ja porraselementtejä',
      'Palopäädyt ja muut palo-osastoivat rakenteet valmiina elementteinä',
      'Ympärivuotinen tehdasvalmistus Kankaanpäässä',
      'Asiakas vastasi elementtien asentamisesta työmaalla',
    ],
    referenceReason:
      'Suuressa aluehankkeessa arvo syntyy siitä, että jokainen seuraava toimitus on yhtä hallittu kuin ensimmäinen. Verstaantiellä ja Leppätiellä julkisivut paneloitiin ja pintamaalattiin tehtaalla, ja myös huoneistojen väliset seinät, terassit, portaat, räystäät sekä palo-osastoivat rakenteet toimitettiin pitkälle valmiina. Hietakulma ja asiakas suunnittelivat rakennuskohtaiset toimitukset yhdessä, joten elementit saapuivat työmaalle oikeassa järjestyksessä ja oikeaan aikaan asiakkaan asennettaviksi. Rakennusliike sai tasaisen tuotantovirran, ennakoitavat työvaiheet ja saman laatutason noin 50 kotiin – vuodenajasta riippumatta.',
  },
  {
    slug: 'hankreetintie-pori',
    title: 'Hankreetintie 189, Pori',
    subtitle: 'Yksilöllinen puukuitueristetty koti ilman pakettitalon rajoja',
    description:
      'Hankreetintiellä lähtökohtana oli asiakkaan oma talo, omat materiaalivalinnat ja haluttu tapa rakentaa. Hietakulma sovitti kaksikerroksisen kodin seinäkorkeudet, elementtijaon ja toimituksen valmiusasteen juuri tähän hankkeeseen. Puukuiturakenteisissa seinäelementeissä käytettiin 250 mm Hunton Nativo -eristettä, Hunton-tuulensuojalevyä ja Intello-höyrynsulkua.',
    location: 'Pori',
    type: 'Omakotitalo',
    category: 'pientalot',
    customerType: 'Yksityinen rakennuttaja',
    deliveryScope: 'Rakenne- ja elementtisuunnittelu, Hunton-eristetyt seinäelementit, Kerto-välipohja-, parveke- ja räystäselementit, ikkunat, 21 kattoristikkoa, kattotarvikkeet ja asennus',
    year: '2025',
    heroImage: '/images/kohteet/hankreetintie-pori/hankreetintie-01.webp',
    thumbnailImage: '/images/kohteet/hankreetintie-pori/hankreetintie-01.webp',
    galleryImages: [
      { src: '/images/kohteet/hankreetintie-pori/hankreetintie-01.webp', alt: 'Hankreetintie, Pori — valmis talo 1' },
      { src: '/images/kohteet/hankreetintie-pori/hankreetintie-02.webp', alt: 'Hankreetintie, Pori — valmis talo 2' },
      { src: '/images/kohteet/hankreetintie-pori/hankreetintie-03.webp', alt: 'Hankreetintie, Pori — valmis talo 3' },
      { src: '/images/kohteet/hankreetintie-pori/hankreetintie-rakennus-01.webp', alt: 'Hankreetintie, Pori — rakennusvaihe 1' },
      { src: '/images/kohteet/hankreetintie-pori/hankreetintie-rakennus-02.webp', alt: 'Hankreetintie, Pori — rakennusvaihe 2' },
    ],
    facts: [
      'Valmistumisvuosi 2025',
      'Yksilöllinen kaksikerroksinen omakotitalo',
      '250 mm Hunton Nativo -puukuitueristettä ja 25 mm Hunton-tuulensuojalevy',
      'Intello-höyrynsulku myös yläpohjassa',
      'Seinäkorkeudet ja elementtien mitat sovitettu asiakkaan kanssa',
      'Seinä-, Kerto-välipohja-, parveke- ja räystäselementtejä',
      '21 kattoristikkoa sekä rakenteiden asennus',
      'Osa ulkoverhouksesta rajattiin asiakkaan toiveesta toimituksen ulkopuolelle',
    ],
    referenceReason:
      'Hankreetintie on vastaus yksityisrakentajan olennaiseen kysymykseen: voiko elementtirakentamisessa silti tehdä aidosti oman talon? Voi. Asiakkaan arkkitehtuuri, puukuitueristeet ja toivottu rakentamistapa ohjasivat sekä rakenteita että toimitusrajaa. Hietakulma suunnitteli niistä yhteensopivan kokonaisuuden, johon kuuluivat seinät, Kerto-välipohja, parveke, räystäät, ristikot ja sovitut asennukset. Osa ulkoverhouksesta jätettiin tarkoituksella asiakkaan toteutettavaksi. Asiakas sai siis apua juuri niihin vaiheisiin, joissa tehdasvalmistus tuo eniten varmuutta – ilman että oma päätösvalta tai materiaalitoiveet katosivat.',
  },
  {
    slug: 'vesikkotie-vantaa',
    title: 'As Oy Vantaan Vesikkotie 12',
    subtitle: 'Kuusi kotia, joissa lasiterassit ja runkoratkaisut suunniteltiin yhtenä kokonaisuutena',
    description:
      'As Oy Vantaan Vesikkotie 12:ssa kolme paritaloa toteutettiin yhtenä hallittuna elementtikokonaisuutena. Takapihojen lasiterassit huomioitiin jo runkojen ja elementtien suunnittelussa, joten niiden liittymiä ei tarvinnut ratkaista erillisenä työmaavaiheena. Ulkoseinien yhtenäinen Isover Facade EJ-32 -tuulensuojaeriste ja osassa elementeistä käytetty jäykistävä TS9-kipsi yhdistävät energiatehokkuuden ja rakenteellisen toimivuuden.',
    location: 'Vantaa',
    type: 'Paritalot',
    category: 'paritalot',
    customerType: 'Kiinteistökehittäjä',
    deliveryScope: 'Puuelementit, integroitujen lasiterassien runkorakenteet, palo-osastoivat ratkaisut ja kattoristikot kolmeen paritaloon',
    year: '2025',
    heroImage: '/images/kohteet/vesikkotie-vantaa/vesikkotie-markkinointi-01.webp',
    thumbnailImage: '/images/kohteet/vesikkotie-vantaa/vesikkotie-markkinointi-01.webp',
    galleryImages: [
      { src: '/images/kohteet/vesikkotie-vantaa/vesikkotie-markkinointi-01.webp', alt: 'As Oy Vantaan Vesikkotie 12 — valmis paritalo' },
      { src: '/images/kohteet/vesikkotie-vantaa/vesikkotie-markkinointi-02.webp', alt: 'Vesikkotien paritalon metsäinen terassijulkisivu' },
      { src: '/images/kohteet/vesikkotie-vantaa/vesikkotie-markkinointi-03.webp', alt: 'Vesikkotien katettu terassi ja metsämaisema' },
      { src: '/images/kohteet/vesikkotie-vantaa/vesikkotie-markkinointi-04.webp', alt: 'Vesikkotien kodin valoisa olohuone' },
      { src: '/images/kohteet/vesikkotie-vantaa/vesikkotie-markkinointi-05.webp', alt: 'Vesikkotien kodin keittiö' },
      { src: '/images/kohteet/vesikkotie-vantaa/vesikkotie-markkinointi-06.webp', alt: 'Vesikkotien kodin sauna' },
      { src: '/images/kohteet/vesikkotie-vantaa/vesikkotie-markkinointi-07.webp', alt: 'Vesikkotien kodin kylpyhuone' },
      { src: '/images/kohteet/vesikkotie-vantaa/vesikkotie-markkinointi-08.webp', alt: 'As Oy Vantaan Vesikkotie 12 — koko alue ilmasta' },
    ],
    facts: [
      'Valmistumisvuosi 2025',
      'Kolme yksitasoista paritaloa',
      'Kuusi 90 m²:n asuntoa',
      'Puuelementit kolmeen asuinrakennukseen',
      'Takapihojen lasiterassit integroitu rakennusten rakenteisiin',
      '16 mm Isover Facade EJ-32 -tuulensuojaeriste rungon ulkopuolella',
      'Osassa seinäelementeistä lisäksi jäykistävä TS9-kipsilevytys',
      'Palo-osastoivat rakenteet valmiiksi huomioituina',
      'Kattoristikot samasta toimituskokonaisuudesta',
      'Oma 2 406 m²:n tontti',
      '12 autopaikkaa',
    ],
    referenceReason:
      'Vesikkotie näyttää, miksi elementtitoimittaja kannattaa ottaa mukaan ennen kuin arkkitehtuuri, talotekniikka ja rakenteet erkanevat omiksi kokonaisuuksikseen. Lasiterassien liittymät, seinien jäykistys, lämmöneristyksen jatkuvuus ja palo-osastoinnit ratkaistiin osana samaa elementtisuunnittelua. Näin työmaalle jäi vähemmän yhteensovitettavaa ja kolmen rakennuksen toimitukset voitiin rytmittää selkeiksi asennusvaiheiksi. Kiinteistökehittäjälle hyöty näkyy kuuden kodin tasaisena laatuna, ennakoitavana työmaana ja rakenteina, joiden toimivuus on mietitty ennen tuotantoa.',
  },
  {
    slug: 'maitiaisentie-tuusula',
    title: 'Maitiaisentie 9, Tuusula',
    subtitle: 'Neljä toimivaa perhekotia tontille – suunnittelusta valmiiksi optimoituina',
    description:
      'Maitiaisentie 9:ssä tavoitteena oli saada puretun rakennuksen tilalle neljä laadukasta perhekotia ja käyttää tontin rakennusoikeus viisaasti. Hietakulma yhdisti arkkitehti-, rakenne-, elementti- ja NR-suunnittelun samaan prosessiin asiakkaan kanssa. Kun tilaratkaisut, kantavat rakenteet, palotekniikka ja talotekniikka sovitettiin yhteen ajoissa, asuinneliöt voitiin maksimoida asumisen laadusta tinkimättä.',
    location: 'Tuusula',
    type: 'Paritalot',
    category: 'paritalot',
    customerType: 'Kiinteistökehittäjä',
    deliveryScope: 'Arkkitehti-, rakenne-, elementti- ja NR-suunnittelu sekä ulko-, huoneistojen välisten seinien, terassien ja räystäiden elementit kahteen paritaloon',
    year: '2024',
    heroImage: '/images/kohteet/maitiaisentie-tuusula/maitiaisentie-01.webp',
    thumbnailImage: '/images/kohteet/maitiaisentie-tuusula/maitiaisentie-01.webp',
    galleryImages: [
      { src: '/images/kohteet/maitiaisentie-tuusula/maitiaisentie-01.webp', alt: 'Maitiaisentie, Tuusula — julkisivu 1' },
      { src: '/images/kohteet/maitiaisentie-tuusula/maitiaisentie-02.webp', alt: 'Maitiaisentie, Tuusula — julkisivu 2' },
      { src: '/images/kohteet/maitiaisentie-tuusula/maitiaisentie-03.webp', alt: 'Maitiaisentie, Tuusula — julkisivu 3' },
      { src: '/images/kohteet/maitiaisentie-tuusula/maitiaisentie-04.webp', alt: 'Maitiaisentie, Tuusula — piha' },
      { src: '/images/kohteet/maitiaisentie-tuusula/maitiaisentie-05.webp', alt: 'Maitiaisentie, Tuusula — yksityiskohta' },
    ],
    facts: [
      'Valmistunut marraskuussa 2024',
      'Vanha rakennus purettiin uuden kokonaisuuden tieltä',
      'Kaksi yksitasoista paritaloa ja neljä asiakkaan kanssa suunniteltua perheasuntoa',
      'Arkkitehti-, rakenne-, elementti- ja NR-suunnittelu',
      'Asuinneliöt optimoitu rakenneratkaisujen avulla',
      'Palotekniikan ja talotekniikan ratkaisut yhteensovitettu suunnitteluryhmässä',
      'Julkisivupaneelit pohja-, väli- ja pintamaalattu tehtaalla',
      'Huoneistojen väliset seinät, terassi- ja räystäselementit sekä palokatkoristikot',
      'Suuret terassit ja lämpimät varastot',
      'Kaksi autopaikkaa / koti ja sähköauton latausvalmius',
    ],
    referenceReason:
      'Maitiaisentie osoittaa, että paras säästö ei aina synny elementin hinnasta vaan paremmasta suunnitteluratkaisusta. Neljä perheasuntoa suunniteltiin asiakkaan kanssa ja niiden pohjat, rakenteet, talotekniikan reitit sekä palotekniset ratkaisut yhteensovitettiin ennen tuotantoa. Näin tontille saatiin enemmän käyttökelpoista asuintilaa ja työmaalta poistettiin kalliita yllätyksiä. Tehtaalla viimeistellyt julkisivut sekä valmiit seinä-, terassi-, räystäs- ja palorakenteet muuttivat suunnitelman toistettavaksi rakennusjärjestelmäksi. Kiinteistökehittäjä sai neljä myytävää perhekotia, tehokkaan tontinkäytön ja yhden suunnitteluketjun ideasta valmistukseen.',
  },
  {
    slug: 'satakunnan-autopinta',
    title: 'Satakunnan Autopinnan Porin toimipiste',
    subtitle: 'Tuotantoprosessin ympärille suunniteltu 1 450 m²:n vauriokorjaamo ja automaalaamo',
    description:
      'Satakunnan Autopinnan uutta Porin toimipistettä ei suunniteltu tyhjän hallin vaan työn sujuvuuden ympärille. Asiakkaan 3D- ja 2D-mallinnetut korjaamo- ja maalaamolinjastot sovitettiin 1 450 m²:n P3-paloluokan rakennukseen ennen rakenteiden lukitsemista. Yli viisimetriset seinät, kaksikerroksiset toimisto- ja sosiaalitilat, palo-osastoinnit ja näyttävä sisäänkäynti toteutettiin samaan puuelementtijärjestelmään.',
    location: 'Pori',
    type: 'Halli',
    category: 'toimitilat',
    customerType: 'Toimitilarakentaja',
    deliveryScope: '112 puuelementtiä, massiivipuu- ja Kerto LVL -välipohjat, kantavat ja palo-osastoivat väliseinät, enintään 18-metriset NR-ristikot, sisäänkäynnin kattoelementti, räystäselementit sekä kattotarvikkeet',
    year: '2024',
    heroImage: '/images/kohteet/satakunnan-autopinta/autopinta-pori-01.webp',
    thumbnailImage: '/images/kohteet/satakunnan-autopinta/autopinta-pori-01.webp',
    galleryImages: [
      { src: '/images/kohteet/satakunnan-autopinta/autopinta-pori-01.webp', alt: 'Satakunnan Autopinnan Porin toimipiste — valmis halli' },
    ],
    facts: [
      'Valmistunut keväällä 2024',
      '1 450 m²:n toimitilahalli',
      'Helmentie 1, 28360 Pori',
      'Vauriokorjaamo- ja automaalaamotilat',
      'P3-paloluokan teollisuus- ja toimitilarakennus',
      'Tuotantolinjastot sovitettu rakennukseen 3D- ja 2D-mallien avulla',
      '112 puuelementtiä',
      'Noin 1 740 m² elementtipinta-alaa',
      '62 ulkoseinä- ja 31 väliseinäelementtiä',
      'Hallin vapaa korkeus noin 5,5 metriä',
      'Suurimmat pystyelementit noin 5,1 × 3,3 metriä',
      'Massiivipuu- ja Kerto LVL -välipohjaelementtejä',
      'Enintään 18 metriä pitkiä NR-ristikoita',
      'Peltiverhouksen koolaus ja sisäpuolen kipsilevytys valmiina seinäelementeissä',
      'Kantavia ja palo-osastoivia väliseiniä sekä räystäs- ja julkisivuelementtejä',
      'Pääosin talvella toteutettu elementtiasennus',
    ],
    referenceReason:
      'Satakunnan Autopinta on referenssi asiakkaalle, joka miettii, voiko suuri ja teknisesti vaativa halli todella olla puuelementtirakenteinen. Voi – kun rakennus suunnitellaan käyttötarkoituksesta lähtien. Hietakulman hallielementtiratkaisulla jopa 5,1 metriä korkeat seinät valmistettiin yhtenäisinä elementteinä. Peltiverhouksen koolaus, sisäpuolen kipsilevytys ja tiiviit rakennekerrokset tehtiin valmiiksi tehtaalla, ja samaan toimitukseen kuuluivat massiivipuu- ja Kerto LVL -välipohjat, palo-osastoivat seinät, enintään 18-metriset ristikot, räystäät ja kattotarvikkeet. Asiakas sai energiatehokkaan rakennuksen, joka voitiin pystyttää nopeasti myös talvella. Ennen kaikkea tila palvelee juuri sitä prosessia, jota varten se rakennettiin.',
  },
  {
    slug: 'as-oy-nokian-tokeenkatu-8',
    title: 'As Oy Nokian Tokeenkatu 8',
    subtitle: 'Seitsemän erilaista kotia – yksi hallittu rakenne- ja toimituskokonaisuus',
    description:
      'As Oy Nokian Tokeenkatu 8 yhdistää samaan rivitaloon neljä yksitasoista ja kolme kaksitasoista kotia. Erilaiset rakennuskorkeudet, easi-joist®-välipohjat, lasitetut terassit, parvekkeet ja vaativat palo-osastoinnit sovitettiin yhteen jo elementtisuunnittelussa. Hietakulman 61 elementin toimitus kattoi noin 1 155 m² rakenteita sekä asuinrakennukseen että lämpimiä varastoja sisältävään talousrakennukseen.',
    location: 'Nokia',
    type: 'Rivitalo',
    category: 'rivitalot',
    customerType: 'Perustajaurakoitsija',
    deliveryScope: 'Ulko- ja väliseinäelementit, easi-joist®-välipohjaelementit, parveke-, terassi- ja kattoelementit, palo-osastoinnit sekä optimoidut elementit asuin- ja talousrakennukseen',
    year: '2024',
    heroImage: '/images/kohteet/kirjavaisenkatu-40/huunala-01-piha.webp',
    thumbnailImage: '/images/kohteet/kirjavaisenkatu-40/huunala-01-piha.webp',
    galleryImages: [
      { src: '/images/kohteet/kirjavaisenkatu-40/huunala-01-piha.webp', alt: 'Tokeenkatu 8:n ja 9:n valmis yhteispiha sekä lasitetut julkisivut' },
      { src: '/images/kohteet/kirjavaisenkatu-40/huunala-02-lasijulkisivu.webp', alt: 'Tokeenkadun kaksikerroksisen asuinrakennuksen lasitettu terassijulkisivu' },
      { src: '/images/kohteet/kirjavaisenkatu-40/huunala-03-sisaankaynnit.webp', alt: 'Tokeenkadun asuntojen puuverhoillut sisäänkäynnit ja katokset' },
      { src: '/images/kohteet/kirjavaisenkatu-40/huunala-04-lasiterassi.webp', alt: 'Tokeenkadun lasitettu terassi sisältä' },
      { src: '/images/kohteet/kirjavaisenkatu-40/huunala-05-talousrakennus.webp', alt: 'Tokeenkadun talousrakennus varastoineen ja autokatoksineen' },
      { src: '/images/kohteet/kirjavaisenkatu-40/huunala-06-pihakokonaisuus.webp', alt: 'Tokeenkatu 8:n ja 9:n valmis piha-alue ja asuinrakennukset' },
      { src: '/images/kohteet/as-oy-nokian-tokeenkatu-8/tokeenkatu-havainne-01.webp', alt: 'As Oy Nokian Tokeenkatu 8 — havainnekuva sisäänkäyntijulkisivusta' },
      { src: '/images/kohteet/as-oy-nokian-tokeenkatu-8/tokeenkatu-havainne-02.webp', alt: 'As Oy Nokian Tokeenkatu 8 — havainnekuva kaksitasoisista kodeista' },
      { src: '/images/kohteet/as-oy-nokian-tokeenkatu-8/tokeenkatu-havainne-03.webp', alt: 'As Oy Nokian Tokeenkatu 8 — havainnekuva yksitasoisista kodeista' },
      { src: '/images/kohteet/as-oy-nokian-tokeenkatu-8/tokeenkatu-01.webp', alt: 'As Oy Nokian Tokeenkatu 8 — rakennustyömaa' },
    ],
    facts: [
      'Valmistumisvuosi 2024',
      'Seitsemän 74–109 m²:n asuntoa',
      'Neljä yksitasoista ja kolme osittain kaksitasoista kotia',
      'Jokaisella kodilla katettu ja täyslasitettu terassi',
      'Kaksitasoisiin koteihin liittyvät parveke-elementit',
      'easi-joist®-välipohjaelementit talotekniikan joustavaan reititykseen',
      'Katto- ja räystäselementtejä valmiiksi maalattuine puuosineen',
      'Vaativat palo-osastoivat rakenteet',
      'Talousrakennus lämpimine varastoineen',
      '61 puuelementtiä',
      'Noin 1 155 m² elementtipinta-alaa',
      'Energialuokka A',
      'Maalämpö ja vesikiertoinen lattialämmitys',
      '6 kWp:n aurinkovoimala',
    ],
    referenceReason:
      'Tokeenkatu näyttää, miten perustajaurakoitsija voi tarjota samassa yhtiössä erilaisia asuntoja menettämättä elementtirakentamisen tehokkuutta. Yksi- ja kaksikerroksisten osien liitokset, talotekniikalle tilaa antavat easi-joist®-välipohjat, terassit, parvekkeet ja palo-osastoinnit suunniteltiin yhtenä järjestelmänä. Myös lämpimät varastot sisältävä talousrakennus optimoitiin samaan toimitukseen. Rakennuttaja sai arkkitehtonisesti vaihtelevan mutta tuotannollisesti hallitun kokonaisuuden – seitsemän myytävää kotia, ennakoitavan rungon ja vähemmän työmaalla ratkaistavia yksityiskohtia.',
  },
  {
    slug: 'levin-atrin-atmos',
    title: 'Levin Atrin Atmos',
    subtitle: 'Kankaanpäässä pitkälle valmiiksi – Levillä nopeasti säältä suojaan',
    description:
      'Levin Atrin Atmos suunniteltiin olosuhteisiin, joissa työmaalla käytetty aika on arvokasta ja pitkä kuljetusmatka on hallittava tarkasti. Kahden 118 m²:n loma-asunnon seinät, välipohjat ja lämpimät kattoelementit valmistettiin pitkälle valmiiksi Kankaanpäässä, ja myös talousrakennus kuului toimitukseen. Kuljetukset optimoitiin täysiksi kuormiksi ja kaavan mukainen ilme viimeisteltiin leveällä, Kanto-sävyyn kuultomaalatulla hirsiponttipaneelilla.',
    location: 'Kittilä / Levi',
    type: 'Loma-asunto',
    category: 'loma-asunnot',
    customerType: 'Loma-asuntojen rakennuttaja',
    deliveryScope: 'Seinä-, easi-joist®-välipohja- ja lämpimät kattoelementit kahteen loma-asuntoon sekä talousrakennuksen seinäelementit, kattoristikot ja vesikatemateriaalit',
    year: '2026',
    heroImage: '/images/kohteet/levin-atrin-atmos/atrin-atmos-01.webp',
    thumbnailImage: '/images/kohteet/levin-atrin-atmos/atrin-atmos-01.webp',
    galleryImages: [
      { src: '/images/kohteet/levin-atrin-atmos/atrin-atmos-01.webp', alt: 'Levin Atrin Atmos — talvinen julkisivu' },
      { src: '/images/kohteet/levin-atrin-atmos/atrin-atmos-02.webp', alt: 'Levin Atrin Atmos — olohuone' },
      { src: '/images/kohteet/levin-atrin-atmos/atrin-atmos-03.webp', alt: 'Levin Atrin Atmos — keittiö ja ruokailutila' },
      { src: '/images/kohteet/levin-atrin-atmos/atrin-atmos-04.webp', alt: 'Levin Atrin Atmos — korkea oleskelutila' },
      { src: '/images/kohteet/levin-atrin-atmos/atrin-atmos-05.webp', alt: 'Levin Atrin Atmos — makuuhuone' },
    ],
    facts: [
      'Kaksi 118 m²:n loma-asuntoa',
      'Valmistumisvuosi 2026',
      'Leveä 28 × 195 mm:n vaakapaneeli kuultomaalattuna sävyyn Tikkurila 5077 Kanto',
      'easi-joist®-välipohjaelementit Kerto- ja Kaisa-palkkirakentein',
      'Lämpimissä kattoelementeissä alushuopa, OSB/raakapontti, 400 mm eriste, höyrynsulku ja alapuolinen koolaus',
      'Talousrakennuksen seinäelementit, kattoristikot ja vesikatemateriaalit',
      'Toimitukset optimoitu täysiksi kuormiksi Kankaanpäästä Leville',
      'Energialuokka B',
      'Ilma-vesilämpöpumppu ja vesikiertoinen lattialämmitys',
    ],
    referenceReason:
      'Atrin Atmos vastaa rakennuttajan käytännön huoleen: miten vaativa loma-asuntokohde saadaan nopeasti säältä suojaan Levillä ilman, että laatu tai arkkitehtuuri kärsii? Ratkaisu oli siirtää mahdollisimman paljon työtä tehtaalle. Seinäelementtien lisäksi toimitettiin easi-joist®-välipohjat ja lämpimät kattoelementit, joissa olivat valmiina kantavat rakenteet, 400 mm eristettä, höyrynsulku, alushuopa ja alapuolinen koolaus. Talousrakennus toteutettiin osana samaa kokonaisuutta. Täysiksi optimoidut kuormat pitivät pitkän kuljetusmatkan tehokkaana, ja leveä kuultomaalattu puuverhous säilytti Levin ympäristöön sopivan ilmeen. Rakennuttaja sai nopean työmaavaiheen, hallitun logistiikan ja kolme keskenään yhteensopivaa rakennusta yhdeltä toimittajalta.',
  },
];

export function getKohdeBySlug(slug: string): Kohde | undefined {
  return kohteet.find((k) => k.slug === slug);
}

export function getAllKohdeSlugs(): string[] {
  return kohteet.map((k) => k.slug);
}
