import { Kohde } from '@/types/content';

export const kohteet: Kohde[] = [
  {
    slug: 'kivikolunkatu-7-nokia',
    title: 'Kivikolunkatu 7 A',
    subtitle: 'Paritalo, joka tuntuu kahdelta omalta kodilta',
    description:
      'Kivikolunkatu 7 A:ssa paritalon tehokkuus kohtaa omakotitalon yksityisyyden. Kaksi yksitasoista kotia yhdistyvät vain autokatoksen kautta, joten rakennus hahmottuu kahdeksi omaksi talokseen. Hietakulma vei kokonaisuuden suunnittelusta pitkälle esivalmistettuihin rakenteisiin ja hallittuun asennukseen.',
    location: 'Nokia',
    type: 'Paritalo',
    category: 'paritalot',
    customerType: 'Ammattirakennuttaja',
    deliveryScope: 'Rakenne- ja elementtisuunnittelu, ikkunalliset puuelementit, palo-osastoivat rakenteet, räystäselementit, 53 kattoristikkoa ja asennus',
    year: '2026',
    featured: true,
    heroImage: '/images/kohteet/kivikolunkatu-7/kivikolunkatu-01.webp',
    thumbnailImage: '/images/kohteet/kivikolunkatu-7/kivikolunkatu-01.webp',
    galleryImages: [
      { src: '/images/kohteet/kivikolunkatu-7/kivikolunkatu-01.webp', alt: 'Kivikolunkatu 7 A:n valmis paritalo Nokialla' },
      { src: '/images/kohteet/kivikolunkatu-7/kivikolunkatu-02.webp', alt: 'Kivikolunkadun sisäänkäyntijulkisivu ja autokatos' },
      { src: '/images/kohteet/kivikolunkatu-7/kivikolunkatu-03.webp', alt: 'Kivikolunkadun katettu terassi' },
      { src: '/images/kohteet/kivikolunkatu-7/kivikolunkatu-04.webp', alt: 'Kivikolunkadun valoisa olohuone ja avokeittiö' },
      { src: '/images/kohteet/kivikolunkatu-7/kivikolunkatu-05.webp', alt: 'Kivikolunkadun ruokailu- ja oleskelutila' },
      { src: '/images/kohteet/kivikolunkatu-7/kivikolunkatu-06.webp', alt: 'Kivikolunkadun moderni keittiö' },
      { src: '/images/kohteet/kivikolunkatu-7/kivikolunkatu-07.webp', alt: 'Kivikolunkadun makuuhuone' },
      { src: '/images/kohteet/kivikolunkatu-7/kivikolunkatu-08.webp', alt: 'Kivikolunkadun kylpyhuone' },
      { src: '/images/kohteet/kivikolunkatu-7/kivikolunkatu-09.webp', alt: 'Kivikolunkadun sauna' },
    ],
    facts: [
      'Valmistumisvuosi 2026',
      'Kaksi yksitasoista kotia',
      '107 m² asuintilaa ja 121 m² kokonaisalaa / koti',
      'Koteja yhdistää autokatos — ei yhteistä asuinseinää',
      'Noin 40 m²:n terassi, pääosin katettu',
      'Poistoilmalämpöpumppu ja vesikiertoinen lattialämmitys',
      '53 kattoristikkoa',
      'Elementtien, ristikoiden ja erikoisrakenteiden asennus',
    ],
    referenceReason:
      'Kivikolunkatu näyttää, mitä yhdeltä toimittajalta saatu kokonaisuus merkitsee ammattirakennuttajalle: vähemmän rajapintoja, ennakoitavampi työmaa ja rakenteet, jotka sopivat toisiinsa jo suunnittelupöydällä. Ikkunalliset seinäelementit, palo-osastointi, räystäät, ristikot ja asennus muodostivat yhden hallitun toimituksen. Lopputulos tekee paritalosta poikkeuksellisen yksityisen ja arkkitehtonisesti eheän.',
  },
  {
    slug: 'kirjavaisenkatu-40',
    title: 'Kirjavaisenkatu 40',
    subtitle: 'Kaksi asuinrakennusta, seitsemän kotia ja vahva arkkitehtoninen ilme',
    description:
      'Kirjavaisenkatu 40 eli Asunto Oy Tampereen Huunalan Herttua on seitsemän kodin yhtiö kahdessa asuinrakennuksessa. Tehdasvalmisteinen puurunko mahdollisti erilaiset asuntotyypit ja näyttävät julkisivut, joissa osa seinäelementeistä toimitettiin Aquapanel-pintaisina työmaalla rapattaviksi.',
    location: 'Tampere',
    type: 'Rivitalo',
    category: 'rivitalot',
    customerType: 'Perustajaurakoitsija',
    deliveryScope: 'Puuelementit kahteen asuinrakennukseen, työmaalla rapatut Aquapanel-pintaiset seinäelementit sekä talousrakennus- ja ristikkokokonaisuus',
    year: '2025',
    heroImage: '/images/kohteet/kirjavaisenkatu-40/b7-01_DJI_0965-HDR.webp',
    thumbnailImage: '/images/kohteet/kirjavaisenkatu-40/b7-01_DJI_0965-HDR.webp',
    galleryImages: [
      { src: '/images/kohteet/kirjavaisenkatu-40/b7-01_DJI_0965-HDR.webp', alt: 'Kirjavaisenkatu 40 — ilmakuva' },
      { src: '/images/kohteet/kirjavaisenkatu-40/b7-02_DJI_0955-HDR.webp', alt: 'Kirjavaisenkatu 40 — ilmakuva 2' },
      { src: '/images/kohteet/kirjavaisenkatu-40/b7-03_DJI_0935-HDR.webp', alt: 'Kirjavaisenkatu 40 — ilmakuva 3' },
      { src: '/images/kohteet/kirjavaisenkatu-40/b7-04_DJI_0895-HDR.webp', alt: 'Kirjavaisenkatu 40 — ilmakuva 4' },
      { src: '/images/kohteet/kirjavaisenkatu-40/b7-06_B7 musta.webp', alt: 'Kirjavaisenkatu 40 — julkisivu' },
      { src: '/images/kohteet/kirjavaisenkatu-40/b7-07_1KUV0829-HDR.webp', alt: 'Kirjavaisenkatu 40 — sisäkuva 1' },
      { src: '/images/kohteet/kirjavaisenkatu-40/b7-08_1KUV0849-HDR.webp', alt: 'Kirjavaisenkatu 40 — sisäkuva 2' },
      { src: '/images/kohteet/kirjavaisenkatu-40/b7-10_1KUV0904-HDR.webp', alt: 'Kirjavaisenkatu 40 — sisäkuva 3' },
      { src: '/images/kohteet/kirjavaisenkatu-40/b7-11_1KUV0924-HDR.webp', alt: 'Kirjavaisenkatu 40 — sisäkuva 4' },
      { src: '/images/kohteet/kirjavaisenkatu-40/b7-14_1KUV0929-HDR.webp', alt: 'Kirjavaisenkatu 40 — sisäkuva 5' },
      { src: '/images/kohteet/kirjavaisenkatu-40/yleiskuva-1KUV6096-HDR.webp', alt: 'Kirjavaisenkatu 40 — yleiskuva' },
    ],
    facts: ['Valmistumisvuosi 2025', 'Seitsemän 87–97 m²:n kotia', 'Kaksi asuinrakennusta ja talousrakennus', 'Rakennus B: 47 elementtiä ja noin 964 m² elementtipinta-alaa', 'Maalämpö, aurinkosähkö ja energialuokka A', 'Aquapanel-pintaisia seinäelementtejä, jotka rapattiin työmaalla'],
    referenceReason: 'Kirjavaisenkatu osoittaa, ettei tehokas elementtirakentaminen rajaa arkkitehtuuria tai julkisivumateriaaleja. Kahden asuinrakennuksen erilaiset asuntotyypit, lähes tuhannen neliön yksittäinen elementtitoimitus ja työmaalla rapatut Aquapanel-pintaiset seinäelementit yhdistyivät hallittavaksi kokonaisuudeksi. Perustajaurakoitsijalle tämä tarkoittaa näyttävää lopputulosta, tarkoituksenmukaista esivalmistusastetta ja ennakoitavampaa työmaata.',
  },
  {
    slug: 'leppatie-pori',
    title: 'Leppätie 5–9, Pori',
    subtitle: 'Sarjallista elementtirakentamista usean rakennuksen mittakaavassa',
    description:
      'Leppätie 5–9 on osa Porin Leppätien ja Verstaantien laajaa asuinkokonaisuutta. Hietakulma valmisti puuelementtejä useisiin rivitaloihin ja talousrakennukseen sekä kattoristikoita osaan rakennuksista. Toistuva rakennusjärjestelmä toi tehokkuutta tehtaalle ja työmaalle säilyttäen alueen pientalomaisen ilmeen.',
    location: 'Pori',
    type: 'Rivitalo',
    category: 'rivitalot',
    customerType: 'Rakennusliike / kiinteistökehittäjä',
    deliveryScope: 'Puuelementit useisiin rivitaloihin ja talousrakennukseen sekä rakennuskohtaisia kattoristikkotoimituksia',
    year: '2023–2024',
    heroImage: '/images/kohteet/leppatie-pori/leppatie-verstaantie-01.webp',
    thumbnailImage: '/images/kohteet/leppatie-pori/leppatie-verstaantie-01.webp',
    galleryImages: [
      { src: '/images/kohteet/leppatie-pori/leppatie-verstaantie-01.webp', alt: 'Leppätien eli Verstaantien rivitalokokonaisuus Porissa' },
      { src: '/images/kohteet/leppatie-pori/leppatie-verstaantie-02.webp', alt: 'Leppätien rivitalon sisäänkäyntijulkisivu iltavalossa' },
      { src: '/images/kohteet/leppatie-pori/leppatie-verstaantie-03.webp', alt: 'Leppätien rivitalon lasitetut terassit' },
      { src: '/images/kohteet/leppatie-pori/leppatie-verstaantie-04.webp', alt: 'Leppätien kohteen talousrakennus' },
      { src: '/images/kohteet/leppatie-pori/leppatie-verstaantie-05.webp', alt: 'Leppätien rivitalon terassijulkisivu' },
      { src: '/images/kohteet/leppatie-pori/leppatie-01.webp', alt: 'Leppätie, Pori — julkisivu 1' },
      { src: '/images/kohteet/leppatie-pori/leppatie-02.webp', alt: 'Leppätie, Pori — julkisivu 2' },
      { src: '/images/kohteet/leppatie-pori/leppatie-03.webp', alt: 'Leppätie, Pori — julkisivu 3' },
      { src: '/images/kohteet/leppatie-pori/leppatie-04.webp', alt: 'Leppätie, Pori — piha-alue' },
      { src: '/images/kohteet/leppatie-pori/leppatie-05.webp', alt: 'Leppätie, Pori — yksityiskohta' },
    ],
    facts: ['Leppätien ja Verstaantien yhteinen aluekokonaisuus', 'Useita erillisiä rivitalorakennuksia', 'Puuelementit myös talousrakennukseen', 'Rakennuskohtaisia kattoristikkotoimituksia', 'Rakennusliikkeelle toistettava elementtiratkaisu'],
    referenceReason: 'Leppätie on vahva näyttö Hietakulman sarjatuotanto-osaamisesta. Kun sama rakennejärjestelmä toistuu useassa rakennuksessa, suunnittelu tarkentuu, tehdasvalmistus tehostuu ja työmaan rytmi muuttuu ennakoitavaksi. Rakennusliike saa mittakaavaetua ilman, että valmiin asuinalueen ilme muuttuu yksitoikkoiseksi.',
  },
  {
    slug: 'hankreetintie-pori',
    title: 'Hankreetintie 189, Pori',
    subtitle: 'Yksilöllinen koti ja laaja toimituskokonaisuus yksityiselle rakentajalle',
    description:
      'Hankreetintien kaksikerroksinen omakotitalo osoittaa, kuinka yksilöllinen arkkitehtuuri ja pitkälle esivalmistettu rakentaminen tukevat toisiaan. Hietakulman toimitus ulottui suunnittelusta seinä-, välipohja-, terassi- ja räystäselementteihin, ikkunoihin, kattorakenteisiin ja asennukseen.',
    location: 'Pori',
    type: 'Omakotitalo',
    category: 'pientalot',
    customerType: 'Yksityinen rakennuttaja',
    deliveryScope: 'Rakenne- ja elementtisuunnittelu, seinä-, välipohja-, terassi- ja räystäselementit, ikkunat, 21 kattoristikkoa, kattotarvikkeet ja asennus',
    year: '2025',
    heroImage: '/images/kohteet/hankreetintie-pori/hankreetintie-01.webp',
    thumbnailImage: '/images/kohteet/hankreetintie-pori/hankreetintie-01.webp',
    galleryImages: [
      { src: '/images/kohteet/hankreetintie-pori/hankreetintie-01.webp', alt: 'Hankreetintie, Pori — valmis talo 1' },
      { src: '/images/kohteet/hankreetintie-pori/hankreetintie-02.webp', alt: 'Hankreetintie, Pori — valmis talo 2' },
      { src: '/images/kohteet/hankreetintie-pori/hankreetintie-03.webp', alt: 'Hankreetintie, Pori — valmis talo 3' },
      { src: '/images/kohteet/hankreetintie-pori/hankreetintie-rakennus-01.webp', alt: 'Hankreetintie, Pori — rakennusvaihe 1' },
      { src: '/images/kohteet/hankreetintie-pori/hankreetintie-rakennus-02.webp', alt: 'Hankreetintie, Pori — rakennusvaihe 2' },
    ],
    facts: ['Valmistumisvuosi 2025', 'Yksilöllinen kaksikerroksinen omakotitalo', 'Seinä-, välipohja-, terassi- ja räystäselementtejä', 'Ikkuna- ja ulkoverhoustoimitus', '21 kattoristikkoa', 'Rakenteiden asennus ja työmaatarvikkeet'],
    referenceReason: 'Hankreetintie tekee näkyväksi Hietakulman arvon yksityiselle rakentajalle. Yksilöllisestä suunnitelmasta muodostettiin tehtaalla yhteensopiva rakennekokonaisuus, joka sisälsi paljon enemmän kuin seinäelementit. Kun välipohjat, terassit, räystäät, ikkunat, kattoristikot ja asennus sovitetaan yhteen etukäteen, rakentajan ei tarvitse ratkaista samoja rajapintoja työmaalla.',
  },
  {
    slug: 'vesikkotie-vantaa',
    title: 'As Oy Vantaan Vesikkotie 12',
    subtitle: 'Kolmen paritalon kokonaisuus Vantaan Metsolaan',
    description:
      'As Oy Vantaan Vesikkotie 12 on kolmen yksitasoisen paritalon ja kuuden kodin kokonaisuus Vantaan Metsolassa. Hietakulma jakoi toimituksen rakennuskohtaisiin elementti- ja ristikkokokonaisuuksiin, jolloin tehtaan tuotanto, kuljetukset ja työmaan eteneminen voitiin rytmittää hallitusti.',
    location: 'Vantaa',
    type: 'Paritalot',
    category: 'paritalot',
    customerType: 'Kiinteistökehittäjä',
    deliveryScope: 'Puuelementit ja kattoristikot kolmeen paritaloon',
    year: '2025',
    heroImage: '/images/kohteet/vesikkotie-vantaa/vesikkotie-markkinointi-01.webp',
    thumbnailImage: '/images/kohteet/vesikkotie-vantaa/vesikkotie-markkinointi-01.webp',
    galleryImages: [
      { src: '/images/kohteet/vesikkotie-vantaa/vesikkotie-markkinointi-01.webp', alt: 'As Oy Vantaan Vesikkotie 12 — valmis paritalo' },
      { src: '/images/kohteet/vesikkotie-vantaa/vesikkotie-markkinointi-02.webp', alt: 'Vesikkotien paritalon metsäinen terassijulkisivu' },
      { src: '/images/kohteet/vesikkotie-vantaa/vesikkotie-markkinointi-03.webp', alt: 'Vesikkotien katettu terassi ja metsämaisema' },
      { src: '/images/kohteet/vesikkotie-vantaa/vesikkotie-markkinointi-04.webp', alt: 'Vesikkotien kodin valoisa olohuone' },
      { src: '/images/kohteet/vesikkotie-vantaa/vesikkotie-markkinointi-05.webp', alt: 'Vesikkotien kodin keittiö' },
      { src: '/images/kohteet/vesikkotie-vantaa/vesikkotie-markkinointi-06.webp', alt: 'Vesikkotien kodin sauna' },
      { src: '/images/kohteet/vesikkotie-vantaa/vesikkotie-markkinointi-07.webp', alt: 'Vesikkotien kodin kylpyhuone' },
      { src: '/images/kohteet/vesikkotie-vantaa/vesikkotie-markkinointi-08.webp', alt: 'As Oy Vantaan Vesikkotie 12 — koko alue ilmasta' },
    ],
    facts: [
      'Valmistumisvuosi 2025',
      'Kolme yksitasoista paritaloa',
      'Kuusi 90 m²:n asuntoa',
      'Puuelementit kolmeen asuinrakennukseen',
      'Kattoristikot samasta toimituskokonaisuudesta',
      'Oma 2 406 m²:n tontti',
      '12 autopaikkaa',
    ],
    referenceReason:
      'Vesikkotie osoittaa rakennuskohtaisen tuotannonohjauksen hyödyn usean rakennuksen hankkeessa. Kolme saman kokonaisuuden paritaloa voitiin suunnitella, valmistaa ja toimittaa selkeinä työmaavaiheina. Kiinteistökehittäjälle tämä merkitsee tasaista laatua kaikissa kuudessa kodissa, ennakoitavia toimituksia ja vähemmän työmaalla ratkaistavia yksityiskohtia.',
  },
  {
    slug: 'maitiaisentie-tuusula',
    title: 'Maitiaisentie 9, Tuusula',
    subtitle: 'Kaksi yksitasoista paritaloa Tuusulan Mattilaan',
    description:
      'Asunto Oy Tuusulan Maitiaisentie 9 muodostuu kahdesta yksitasoisesta paritalosta ja neljästä kodista. Rakennuskohtaisina kokonaisuuksina valmistetut Hietakulman puuelementit yhdistävät sarjatuotannon tasalaatuisuuden pientalomaiseen mittakaavaan, suuriin terasseihin ja suojaisiin pihoihin.',
    location: 'Tuusula',
    type: 'Paritalot',
    category: 'paritalot',
    customerType: 'Kiinteistökehittäjä',
    deliveryScope: 'Puuelementit kahden paritalon asuntokokonaisuuteen',
    year: '2024',
    heroImage: '/images/kohteet/maitiaisentie-tuusula/maitiaisentie-01.webp',
    thumbnailImage: '/images/kohteet/maitiaisentie-tuusula/maitiaisentie-01.webp',
    galleryImages: [
      { src: '/images/kohteet/maitiaisentie-tuusula/maitiaisentie-01.webp', alt: 'Maitiaisentie, Tuusula — julkisivu 1' },
      { src: '/images/kohteet/maitiaisentie-tuusula/maitiaisentie-02.webp', alt: 'Maitiaisentie, Tuusula — julkisivu 2' },
      { src: '/images/kohteet/maitiaisentie-tuusula/maitiaisentie-03.webp', alt: 'Maitiaisentie, Tuusula — julkisivu 3' },
      { src: '/images/kohteet/maitiaisentie-tuusula/maitiaisentie-04.webp', alt: 'Maitiaisentie, Tuusula — piha' },
      { src: '/images/kohteet/maitiaisentie-tuusula/maitiaisentie-05.webp', alt: 'Maitiaisentie, Tuusula — yksityiskohta' },
    ],
    facts: ['Valmistunut marraskuussa 2024', 'Kaksi yksitasoista paritaloa', 'Neljä kotia', 'Suuret terassit ja lämpimät varastot', 'Kaksi autopaikkaa / koti ja sähköauton latausvalmius', 'Hietakulman puuelementit'],
    referenceReason: 'Maitiaisentie on tiivis esimerkki kiinteistökehittäjän tehokkaasta paritalohankkeesta. Kaksi rakennusta toteutettiin omina tuotantokokonaisuuksinaan, mutta valmiina ne muodostavat yhtenäisen asuinympäristön. Tehdasvalmistus auttaa pitämään neljän kodin rakenteet tasalaatuisina ja työmaan aikataulun hallittavana.',
  },
  {
    slug: 'satakunnan-autopinta',
    title: 'Satakunnan Autopinnan Porin toimipiste',
    subtitle: 'Hietakulman suurin elementtikohde pinta-alalla mitattuna',
    description:
      'Satakunnan Autopinnan Porin toimipiste on 1 450 m²:n vauriokorjaamo ja automaalaamo, jonka 112 puuelementtiä muodostavat Hietakulman ERP-aineiston suurimman kohteen elementtipinta-alalla mitattuna. Toimitus sisälsi ulko- ja väliseinien lisäksi vaaka-, pääty-, palo-osastoivia ja räystäselementtejä.',
    location: 'Pori',
    type: 'Halli',
    category: 'toimitilat',
    customerType: 'Toimitilarakentaja',
    deliveryScope: '112 puuelementin toimitus: ulko- ja väliseinät, vaaka- ja päätyelementit, palo-osastoivat rakenteet sekä räystäselementti',
    year: '2024',
    heroImage: '/images/kohteet/satakunnan-autopinta/autopinta-pori-01.webp',
    thumbnailImage: '/images/kohteet/satakunnan-autopinta/autopinta-pori-01.webp',
    galleryImages: [
      { src: '/images/kohteet/satakunnan-autopinta/autopinta-pori-01.webp', alt: 'Satakunnan Autopinnan Porin toimipiste — valmis halli' },
    ],
    facts: [
      'Valmistunut keväällä 2024',
      '1 450 m²:n toimitilahalli',
      'Helmentie 1, 28360 Pori',
      'Vauriokorjaamo- ja automaalaamotilat',
      '112 puuelementtiä',
      'Noin 1 740 m² elementtipinta-alaa',
      '62 ulkoseinä- ja 31 väliseinäelementtiä',
      'Vaaka-, pääty-, palo- ja räystäselementtejä',
    ],
    referenceReason:
      'Autopinta näyttää Hietakulman kapasiteetin teollisessa mittakaavassa. Yli sadan elementin toimitus ei ollut yhden seinätyypin sarja, vaan kokonaisuus ulko- ja väliseinistä palo-osastoiviin rakenteisiin. Toimitilarakentajalle arvo syntyy siitä, että suuri ja teknisesti vaihteleva runko voidaan valmistaa hallitusti tehtaalla ja viedä työmaalle selkeinä kokonaisuuksina.',
  },
  {
    slug: 'as-oy-nokian-tokeenkatu-8',
    title: 'As Oy Nokian Tokeenkatu 8',
    subtitle: 'Seitsemän kodin rivitalo ja talousrakennus yhtenä elementtitoimituksena',
    description:
      'As Oy Nokian Tokeenkatu 8 on seitsemän kodin puurivitaloyhtiö, jossa yksitasoiset ja osittain kaksitasoiset asunnot muodostavat vaihtelevan mutta yhtenäisen kokonaisuuden. Hietakulman 61 elementin toimitus kattoi noin 1 155 m² elementtipinta-alaa rivitaloon ja erilliseen talousrakennukseen.',
    location: 'Nokia',
    type: 'Rivitalo',
    category: 'rivitalot',
    customerType: 'Perustajaurakoitsija',
    deliveryScope: 'Puuelementit rivitaloon ja talousrakennukseen',
    year: '2024',
    heroImage: '/images/kohteet/as-oy-nokian-tokeenkatu-8/tokeenkatu-havainne-01.webp',
    thumbnailImage: '/images/kohteet/as-oy-nokian-tokeenkatu-8/tokeenkatu-havainne-01.webp',
    galleryImages: [
      { src: '/images/kohteet/as-oy-nokian-tokeenkatu-8/tokeenkatu-havainne-01.webp', alt: 'As Oy Nokian Tokeenkatu 8 — havainnekuva sisäänkäyntijulkisivusta' },
      { src: '/images/kohteet/as-oy-nokian-tokeenkatu-8/tokeenkatu-havainne-02.webp', alt: 'As Oy Nokian Tokeenkatu 8 — havainnekuva kaksitasoisista kodeista' },
      { src: '/images/kohteet/as-oy-nokian-tokeenkatu-8/tokeenkatu-havainne-03.webp', alt: 'As Oy Nokian Tokeenkatu 8 — havainnekuva yksitasoisista kodeista' },
      { src: '/images/kohteet/as-oy-nokian-tokeenkatu-8/tokeenkatu-01.webp', alt: 'As Oy Nokian Tokeenkatu 8 — rakennustyömaa' },
    ],
    facts: [
      'Valmistumisvuosi 2024',
      'Seitsemän 74–109 m²:n asuntoa',
      'Neljä yksitasoista ja kolme osittain kaksitasoista kotia',
      '61 puuelementtiä',
      'Noin 1 155 m² elementtipinta-alaa',
      'Energialuokka A',
      'Maalämpö ja vesikiertoinen lattialämmitys',
      '6 kWp:n aurinkovoimala',
    ],
    referenceReason:
      'Tokeenkatu yhdistää suuren elementtipinta-alan, kaksi rakennusta ja keskenään erilaiset asuntotyypit samaan hallittuun toimitukseen. Perustajaurakoitsijalle Hietakulman ratkaisu tarjoaa yhdenmukaisen rakenteellisen laadun sekä rivitaloon että talousrakennukseen. Energialuokka A, maalämpö ja aurinkosähkö tekevät kohteesta samalla vahvan esimerkin uuden sukupolven yhtiömuotoisesta puurakentamisesta.',
  },
  {
    slug: 'levin-atrin-atmos',
    title: 'Levin Atrin Atmos',
    subtitle: 'Seinä- ja kattoelementit kahteen loma-asuntoon sekä talousrakennus Leville',
    description:
      'Levin Atrin Atmos on kahden 118 m²:n loma-asunnon kokonaisuus lähellä Levin palveluita ja rinteitä. Hietakulma toimitti loma-asuntoihin puu- ja kattoelementit sekä erilliseen talousrakennukseen seinäelementit ja kattoristikot. Kokonaisuus mahdollisti korkeat oleskelutilat, vahvan puurakentamisen ilmeen ja hallitun toimituksen Kankaanpäästä Kittilään.',
    location: 'Kittilä / Levi',
    type: 'Loma-asunto',
    category: 'loma-asunnot',
    customerType: 'Loma-asuntojen rakennuttaja',
    deliveryScope: 'Puu- ja kattoelementit kahteen loma-asuntoon sekä talousrakennuksen seinäelementit ja kattoristikot',
    year: '2026',
    heroImage: '/images/kohteet/levin-atrin-atmos/atrin-atmos-01.webp',
    thumbnailImage: '/images/kohteet/levin-atrin-atmos/atrin-atmos-01.webp',
    galleryImages: [
      { src: '/images/kohteet/levin-atrin-atmos/atrin-atmos-01.webp', alt: 'Levin Atrin Atmos — talvinen julkisivu' },
      { src: '/images/kohteet/levin-atrin-atmos/atrin-atmos-02.webp', alt: 'Levin Atrin Atmos — olohuone' },
      { src: '/images/kohteet/levin-atrin-atmos/atrin-atmos-03.webp', alt: 'Levin Atrin Atmos — keittiö ja ruokailutila' },
      { src: '/images/kohteet/levin-atrin-atmos/atrin-atmos-04.webp', alt: 'Levin Atrin Atmos — korkea oleskelutila' },
      { src: '/images/kohteet/levin-atrin-atmos/atrin-atmos-05.webp', alt: 'Levin Atrin Atmos — makuuhuone' },
    ],
    facts: [
      'Kaksi 118 m²:n loma-asuntoa',
      'Valmistumisvuosi 2026',
      'Puu- ja kattoelementit loma-asuntoihin',
      'Talousrakennuksen seinäelementit ja kattoristikot',
      'Energialuokka B',
      'Ilma-vesilämpöpumppu ja vesikiertoinen lattialämmitys',
    ],
    referenceReason:
      'Atrin Atmos osoittaa, että Hietakulman toimituskyky ei pääty lähialueelle eikä yksittäiseen rakennetyyppiin. Loma-asuntojen seinä- ja kattoelementit sekä talousrakennuksen seinät ja kattoristikot muodostivat kolme toisiinsa sovitettua tehdasvalmisteista kokonaisuutta. Korkeat sisätilat, vaativa kattogeometria ja pitkä toimitusmatka tekevät kohteesta vahvan esimerkin arkkitehtonisesti kunnianhimoisesta loma-asuntorakentamisesta.',
  },
];

export function getKohdeBySlug(slug: string): Kohde | undefined {
  return kohteet.find((k) => k.slug === slug);
}

export function getAllKohdeSlugs(): string[] {
  return kohteet.map((k) => k.slug);
}
