// Keep portal models identical while PostgreSQL gets its own migration history.
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const source = fs.readFileSync(path.join(root, 'prisma/schema.prisma'), 'utf8');
const expected = '// Generated by node scripts/postgres-schema.cjs; edit prisma/schema.prisma.\n' + source
  .replace('output   = "../node_modules/.prisma/client"', 'output   = "../../lib/generated/prisma-postgres"')
  .replace('provider = "sqlite"', 'provider = "postgresql"')
  .replace('env("DATABASE_URL")', 'env("POSTGRES_DATABASE_URL")');
if (expected.includes('provider = "sqlite"') || !expected.includes('prisma-postgres')) {
  throw new Error('Unexpected source schema; inspect the PostgreSQL transformation.');
}
const target = path.join(root, 'prisma/postgresql/schema.prisma');
if (process.argv.includes('--check')) {
  if (!fs.existsSync(target) || fs.readFileSync(target, 'utf8') !== expected) {
    throw new Error('PostgreSQL schema is stale. Run node scripts/postgres-schema.cjs.');
  }
} else {
  fs.mkdirSync(path.dirname(target), { recursive: true });
  fs.writeFileSync(target, expected);
}
